### PR TITLE
Fix/async processing

### LINKED ISSUE #29: While loops interrupt draw function
This code: https://trinket.io/python/9c9e124f4b

Should yield this (i.e. a spiraling animation of this figure):

screen shot 2017-12-19 at 12 13 50 pm

From the position of the elipses it seems like the translate() isn't happening.  If so, and it's throwing an error instead, that could account for the difference.

User reported this was a regression since 0.0.5 but I couldn't confirm that.  Seems likely this is a preexisting issue.

Update:

Seems related to while loops. Definite for loops resolve the bug:
https://trinket.io/python/cbf38bc1ce

MWE of bug: https://trinket.io/python/3ece9cbfc5

### LINKED ISSUE #34: loadPixels, pixels
The following code:

```python
def draw():
  loadPixels()
  print pixels[0]
  updatePixels()
```

Should produce `-3355444` repeatedly.  Instead it produces `None`

related: printing `pixels` produces `<processing.ImageProxy object>` on prod and `<_main.ImageProxy object>` on dev.  It should produce a list of `-3355444` for each pixel (in the base case above).

Seems like `pixels` should be a subclass of list or something. http://py.processing.org/reference/pixels.html

Apparently it only exists after `loadPixels()` is called, and then `updatePixels()` will push any mutations you did to it to the current screen.

### PR DESCRIPTION
**Pull request by albertjan**
@eah13 this goes together with forked version of processing that handles async draw functions correctly. 

Fixes #34 
Fixes #29

### CODE REVIEW

**Comment by eah13** [comment]
The bower.json dependency entry should point to 1.6.8 of our fork as of this branch.

**Comment by eah13** [comment]
Also, let's go ahead and bump the bower version so this will be releasable on merge.

**Comment by albertjan** [comment]
Aye!

________________________________

**Comment by eah13** [comment]
This looks great and I haven't been able to find regressions from enableDoubleBuffer besides the event handling stuff.  That's the last Todo I'm aware of, and then we can make enableDoubleBuffer happen by default and ship.

Code I used for testing events: http://elliott-dev.trinket.io/python/845567b898

**Comment by albertjan** [comment]
I’ll get onto events asap ;)

________________________________

**Comment by eah13** [comment]
Sweet.  By my count we've got these items left:

- [ ] Bower version bump
- [ ] Bower dependency update
- [ ] `enableDoubleBuffer` by default

Anything else needed to gt this over the finish line?

**Comment by eah13** [comment]
Still getting the relative coordinates bug you described with the new event propagation http://elliott-dev.trinket.io/python/845567b898

'Touched' appears when the mouse first touches the canvas at all in this case.  Added this to the above list

**Comment by albertjan** [comment]
Yeah I haven’t figured our how to solve that one yet :). Next week!

________________________________

**Comment by albertjan** [comment]
also fixes with #34

**Comment by eah13** [comment]
@albertjan did you test this on trinket? As of 04dc814 the canvas is now blank.

Also, not seeing that the `getPixels` fix addresses the base case in #34.  printing `pixels` still prints an object repr instead of a list.

**Comment by albertjan** [comment]
Did you update processing js? Right I forgot about the repr. My dev env run the build after that hash. I didn’t test the pixels thing on trinket because that has no integration surface.

________________________________

**Comment by albertjan** [comment]
I did a new release of processing-js here: https://github.com/trinketapp/processing-js/releases/tag/1.6.9

**Comment by eah13** [comment]
Do we guarantee that `setup` runs before `draw`?  In this program, seems like `draw` runs before `img` gets overwritten http://elliott-dev.trinket.io/python/dd05f9fda1

**Comment by albertjan** [comment]
Yeah we do guarantee it and it does but somehow it seems like it doesn’t wait for the image to load.

________________________________

**Comment by albertjan** [comment]
Please stop finding bugs 🤣🙏

________________________________

**Comment by albertjan** [comment]
The `draw` function being called before `setup` finishes is because of the `frameRate` call. I’m testing a fix for this now but it’s another change in processing js. I also found another bug that caused exceptions in the setup function to be swallowed. There were two other bugs in the `loadPixels` call and the `pixels` property on image.

**Comment by albertjan** [comment]
I'm gonna merge this so I can do a PR to trinket with the new versions.

**Pull request merged**
